-- 1. Table: parking_zones
-- Represents a geographic parking area (e.g., "Centre Ville")
CREATE TABLE parking_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    hourly_rate DECIMAL(19, 2), -- BigDecimal maps to Decimal
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION
);

-- 2. Table: parking_spots
-- Represents a specific physical spot (e.g., "P-101") inside a zone
CREATE TABLE parking_spots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spot_number VARCHAR(255) NOT NULL UNIQUE,
    sensor_id VARCHAR(255) NOT NULL UNIQUE, -- IoT Link
    status BOOLEAN, -- true = Free, false = Occupied
    zone_id BIGINT,
    CONSTRAINT fk_parking_spot_zone FOREIGN KEY (zone_id) REFERENCES parking_zones(id)
);

-- 3. Table: utilisateur
-- Users synchronized from Clerk (Drivers, Admins, etc.)
CREATE TABLE utilisateur (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    mot_de_passe VARCHAR(255), -- Nullable
    telephone VARCHAR(255),
    role VARCHAR(255) NOT NULL, -- Enum: CONDUCTEUR, ADMINISTRATEUR
    clerk_id VARCHAR(255) UNIQUE
);

-- 4. Table: parking_sessions
-- History of parking transactions
CREATE TABLE parking_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id VARCHAR(255), -- Stores the Clerk ID (String), not a numeric FK to utilisateur
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    total_cost DECIMAL(19, 2),
    status VARCHAR(255), -- Enum: ACTIVE, COMPLETED
    spot_id BIGINT,
    CONSTRAINT fk_parking_session_spot FOREIGN KEY (spot_id) REFERENCES parking_spots(id)
);

-- 5. Table: reclamation
-- User complaints or tickets
CREATE TABLE reclamation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255), -- Clerk ID
    user_email VARCHAR(255),
    user_name VARCHAR(255),
    user_phone VARCHAR(255),
    service_type VARCHAR(255),
    title VARCHAR(255),
    description VARCHAR(255),
    priority VARCHAR(255),
    address VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    attachments_json TEXT, -- @Column(columnDefinition = "TEXT")
    extra_data_json TEXT,  -- @Column(columnDefinition = "TEXT")
    received_at TIMESTAMP
);

-- 6. Table: message_response
-- Admin/Bot responses to reclamations
CREATE TABLE message_response (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reclamation_id BIGINT, -- Logical link to reclamation (No FK constraint in Entity code)
    operator_id VARCHAR(255),
    operator_name VARCHAR(255),
    response_message TEXT, -- @Column(columnDefinition = "TEXT")
    created_at TIMESTAMP
);